# Generated by Django 4.2.10 on 2024-04-01 11:17

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='api_key',
            field=models.CharField(default=users.models.generate_api_key, max_length=255, unique=True),
        ),
    ]
