# Generated by Django 4.2.10 on 2024-04-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_device_api_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='humidity',
            new_name='air_humidity',
        ),
        migrations.RenameField(
            model_name='sensordata',
            old_name='temperature',
            new_name='air_temperature',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='light',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='soil_moisture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='water_level',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
